name-template: 'Next Release 🛒'
tag-template: 'next'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📦 Dependencies'
    label: 'dependencies'
  - title: ⚠️ Changes
    labels:
      - deprecated
  - title: 📄 Documentation
    labels:
      - docs
      - documentation
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
autolabeler:
  - label: 'bug'
    branch:
      - '/(bugfix|fix)\/.+/'
  - label: 'enhancement'
    branch:
      - '/(feature)\/.+/'
replacers:
  - search: '/MARP-(\d+)/g'
    replace: '[MARP-$1](https://1ivy.atlassian.net/browse/MARP-$1)'
commitish: 'master'
filter-by-commitish: true
template: |
  ## Changes

  $CHANGES