name-template: 'v$RESOLVED_VERSION 🛒'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📦 Dependencies'
    label: 'dependencies'
  - title: ⚠️ Changes
    labels:
      - deprecated
  - title: 📄 Documentation
    labels:
      - docs
      - documentation
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'bug'
    branch:
      - '/(bugfix|fix)\/.+/'
  - label: 'enhancement'
    branch:
      - '/(feature)\/.+/'
replacers:
  - search: '/MARP-(\d+)/g'
    replace: '[MARP-$1](https://1ivy.atlassian.net/browse/MARP-$1)'
template: |
  ## Changes

  $CHANGES